CREATE TABLE IF NOT EXISTS public.contact_submission_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contact_submission_attempts_ip_created_idx
  ON public.contact_submission_attempts (ip_hash, created_at DESC);

ALTER TABLE public.contact_submission_attempts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.contact_submission_attempts FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.contact_submission_attempts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.contact_submission_attempts_id_seq TO service_role;

DROP POLICY IF EXISTS "Anyone can submit enquiry" ON public.inbound_contacts;
DROP POLICY IF EXISTS "Public can submit enquiry with consent" ON public.inbound_contacts;
REVOKE INSERT ON public.inbound_contacts FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.inbound_contacts TO service_role;

REVOKE ALL ON FUNCTION public.gocardless_enabled() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gocardless_enabled() TO anon, authenticated;